language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer update --prefer-dist --no-interaction

script:
  - php vendor/bin/php-cs-fixer fix --diff --dry-run -v
  - php vendor/bin/phpunit --verbose